// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Swarmer.Domain.Database;

#nullable disable

namespace Swarmer.Domain.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231227144651_AddBotNameColumnToConfigEntity")]
    partial class AddBotNameColumnToConfigEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Swarmer.Domain.Database.ConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("JsonConfig")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("BotConfigurations", (string)null);
                });

            modelBuilder.Entity("Swarmer.Domain.Database.GameChannel", b =>
                {
                    b.Property<decimal>("StreamChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("TwitchGameId")
                        .HasColumnType("integer");

                    b.HasKey("StreamChannelId", "TwitchGameId");

                    b.ToTable("GameChannels", (string)null);
                });

            modelBuilder.Entity("Swarmer.Domain.Database.StreamMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LingeringSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("OfflineThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("StreamMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
