// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Swarmer.Domain.Database;

#nullable disable

namespace Swarmer.Domain.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322174657_RemoveBotConfigAndChangeSchema")]
    partial class RemoveBotConfigAndChangeSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("swarmer")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Swarmer.Domain.Database.BannedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserLogin")
                        .IsUnique();

                    b.ToTable("BannedUsers", "swarmer");
                });

            modelBuilder.Entity("Swarmer.Domain.Database.GameChannel", b =>
                {
                    b.Property<decimal>("StreamChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("TwitchGameId")
                        .HasColumnType("integer");

                    b.HasKey("StreamChannelId", "TwitchGameId");

                    b.ToTable("GameChannels", "swarmer");
                });

            modelBuilder.Entity("Swarmer.Domain.Database.StreamMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LingeringSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("OfflineThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("StreamMessages", "swarmer");
                });
#pragma warning restore 612, 618
        }
    }
}
